<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit75ef49678de62bb47df3ed61c5ed0be3
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('ConstantContact\ConstantContactForms\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \ConstantContact\ConstantContactForms\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit75ef49678de62bb47df3ed61c5ed0be3', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \ConstantContact\ConstantContactForms\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit75ef49678de62bb47df3ed61c5ed0be3', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\ConstantContact\ConstantContactForms\Composer\Autoload\ComposerStaticInit75ef49678de62bb47df3ed61c5ed0be3::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
